# Menus
Shift+c script-binding select/select-chapter
Ctrl+f script-binding quality_menu/video_formats_toggle
Ctrl+Alt+f script-binding quality_menu/audio_formats_toggle

# Volume
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5
UP add volume 5
DOWN add volume -5

# Subtitle size
Ctrl+WHEEL_UP add sub-scale +0.1
Ctrl+WHEEL_DOWN add sub-scale -0.1

# Seeking
Shift+RIGHT seek 5
Shift+LEFT seek -5
RIGHT seek 10
LEFT seek -10
Ctrl+RIGHT seek 60
Ctrl+LEFT seek -60
Ctrl+Alt+RIGHT seek 300
Ctrl+Alt+LEFT seek -300

# Playlist navigation
p playlist-prev
n playlist-next

# Picture adjustments
a cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"
Ctrl+r cycle-values video-rotate 90 180 270 0
