# shellcheck shell=bash
# shellcheck disable=SC1090

# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# Show a random Fastfetch logo and system summary in interactive Git Bash sessions.
if [[ $- == *i* ]]; then
    ascii_dir="$HOME/.config/fastfetch/ascii"
    had_nullglob=0
    shopt -q nullglob && had_nullglob=1
    shopt -s nullglob
    ascii_files=("$ascii_dir"/*.txt)
    ((had_nullglob)) || shopt -u nullglob

    if ((${#ascii_files[@]})); then
        selected_ascii="${ascii_files[RANDOM % ${#ascii_files[@]}]}"
        if [[ -n "${USERPROFILE:-}" ]]; then
            selected_ascii="$USERPROFILE/.config/fastfetch/ascii/${selected_ascii##*/}"
        else
            selected_ascii="$(cygpath -m "$selected_ascii")"
        fi
        fastfetch --file "$selected_ascii"
    else
        fastfetch
    fi

    unset ascii_dir ascii_files had_nullglob selected_ascii
fi
